fix: Change Websocket to Deno's native method
oslabs-beta/sono.io pull request #10
Opened 2024-07-07 08:31 UTC by KonghaYao

## Description

Hello, I really like the sono.land project! When I started Deno and wanted to implement some related features, I found that it didn't run very well on my Deno version 1.42.3. So I forked this repository and improved the source code based on Deno's documentation about websockets. It runs well in my deno-script and I hope to upgrade the sono version on deno.land.

## Reproduction steps

just run it in latest Deno version

```js
import { Sono } from "https://denopkg.dev/gh/KonghaYao/sono.land@main/src/server.ts?33";
const sono = new Sono();
Deno.serve(async (req) => {
    return sono.connect(req);
});

```

## Checklist

- [x] I've followed the [Contributing guidelines](https://github.com/oslabs-beta/.github/blob/main/docs/CONTRIBUTING.md)
- [x] I've titled my PR according to the [Conventional Commits spec](https://conventionalcommits.org)
- [x] I've added tests that fail without this PR but pass with it
- [x] I've linted, tested, and commented my code
- [x] I've updated documentation (if appropriate)

2024-07-18 01:34 UTC, vin-vu commented on src/server.ts
> +    const { socket, response }: { socket: WebSocket, response: Response } = Deno.upgradeWebSocket(req);
Noted change to Deno's native websocket method here

2024-07-23 18:25 UTC, vin-vu requested changes
Thank you for contributing! 

Please see my comment regarding changes to the readme

2024-07-23 18:25 UTC, vin-vu commented on README.md
> +  import { Sono } from "./server.mts";
I see 2 sono imports on line 53 and 56. Just wanted to check if this was an accident or a placeholder. We can update the import url once the new version is released.

2024-07-24 00:47 UTC, KonghaYao commented on README.md
> +  import { Sono } from "./server.mts";
I carelessly copied the code from the test file into the document, my mistake. 😊 You are free to make any changes to this PR as you see fit.

2024-07-26 00:27 UTC, vin-vu commented on README.md
> +  import { Sono } from "./server.mts";
Sounds good! I removed the duplicate import.

2024-07-26 00:31 UTC, vin-vu approved these changes
I've tested your code locally and everything works. Thanks again for your help! 👍

2024-07-26 00:32 UTC, merged